### ISSUE TITLE
experiment_test_disease_morality test_full_deaths error 'everyone should die with parameters'

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#105]
Having @Sv3tlana take a look at this. I noticed in your tests/experiment_test_disease_mortality.py 2 issues.

The first error, I fixed by setting DiseaseKeys to since the default_ ones are no longer keys.
```
    probability_of_infected_developing_symptoms = 'rel_symp_prob'  # 'default_symp_prob'
    probability_of_symptoms_developing_severe = 'rel_severe_prob'  # 'default_severe_prob'
    probability_of_severe_developing_death = 'rel_death_prob'  # 'default_death_prob'
```

But, the 2nd issue, on test_full_deaths should be looked into. It results in 22 deaths when 1000 are expected:

```
Everyone should die with parameters {'pop_infected': 1000, 'prog_by_age': False, 'rel_symp_prob': 1, 'rel_severe_prob': 1, 'rel_death_prob': 1}. Channel cum_deaths had bad data: 22.0 deaths vs. 1000 people.
22.0 != 1000

Expected :1000
Actual   :22.0
 <Click to see difference>

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.6\helpers\pycharm\teamcity\diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "c:\program files\python36\Lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\program files\python36\Lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1000 != 22.0 : Everyone should die with parameters {'pop_infected': 1000, 'prog_by_age': False, 'rel_symp_prob': 1, 'rel_severe_prob': 1, 'rel_death_prob': 1}. Channel cum_deaths had bad data: 22.0 deaths vs. 1000 people.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\program files\python36\Lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\git\covasim\IDM\covasim\tests\unittests\experiment_test_disease_mortality.py", line 99, in test_full_deaths
    msg=f"Everyone should die with parameters {test_parameters}. "

```

**Comment by cliffckerr** [comment]
Closed by #108
