### ISSUE TITLE
load_population file fails for generated ppl files

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#138]
When I test using synthpops to save_population data, and then try to load that file using load_population, it fails with:

```
Error
Traceback (most recent call last):
  File "c:\program files\python36\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\program files\python36\Lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\git\covasim\mafisher\covasim-1\tests\test_populations.py", line 53, in test_save_synthpops_population
    load_pop = base_sim.load_population(cached_population_filename)
  File "C:\git\covasim\mafisher\covasim-1\covasim\sim.py", line 105, in load_population
    n_actual = len(self.popdict['uid'])
TypeError: 'NoneType' object is not subscriptable
```

Steps to reproduce:

This is what I tried:

```
    def test_save_load_synthpops_population(self):
        self.is_debugging = True

        # Simulation parameters
        params = {
            "pop_size": 100,  # Population size
            "pop_infected": 10,  # Initial infections
            "start_day": "2020-03-20",
            "n_days": 180,
            "pop_type": "synthpops",
            "use_layers": True
        }

        # Store the filename
        cached_population_filename = f'example_population_{params["pop_size"]}.ppl'

        base_sim = cv.Sim(pars=params)
        # save the population
        save_pop = base_sim.save_population(cached_population_filename)
        # now load it
        load_pop = base_sim.load_population(cached_population_filename)

        # and compare
        self.assertEqual(save_pop, load_pop)
```

The ppl file's attached that was generated. [example_population_100.zip](https://github.com/InstituteforDiseaseModeling/covasim/files/4483841/example_population_100.zip)

**Comment by DMistry-IDM** [comment]
If you use a pop size less than 5000 and pop type = 'synthpops' this should raise a NotImplementedError. I'll check this out.

**Comment by cliffckerr** [comment]
Not required for webapp and duplicated on amath-idm so will close for now
