### ISSUE TITLE
Zero size populations produce a runtime warning

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#166]
Working on population size tests, tried running a zero size population and expected an exception. Instead, got a runtime warning and the sim seemed to run fine.

_For model issues:_
```python
import covasim as cv
pop_zero_one_day = {
            'pop_scale': 1,
            'n_days': 100,
            'pop_size': 0,
            'pop_infected': 0
        }
sim = cv.Sim(pars=pop_zero_one_day) # Configure the simulation
sim.run() # Steps required to produce the behavior
```

**Expected behavior**
Probably a ValueError Raised

**Observed Behavior**
```
Initializing sim with 0 people for 100 days
c:\github\covasim\covasim\sim.py:441: RuntimeWarning: invalid value encountered in double_scalars
  r = infections_now/infections_prev
```

**Platform (please complete the following information):**
 - Covasim version: [e.g. 0.27.5]
 - OS: Win10

**Comment by ckerr-IDM** [comment]
I think this is OK -- you do have to set both pop_size and pop_infected to 0, else you get a pretty meaningful error:
```
sim = cv.Sim(pop_size=0)

sim.run()
Initializing sim with 0 people for 60 days
Traceback (most recent call last):

  File "<ipython-input-9-7c6cd8add6f4>", line 1, in <module>
    sim.run()

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 380, in run
    self.initialize()

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 137, in initialize
    self.init_people(**kwargs) # Create all the people (slow)

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 261, in init_people
    self.people.infect(inds=inds)

  File "/home/cliffk/idm/covasim/covasim/people.py", line 283, in infect
    self.susceptible[inds]    = False

IndexError: index 0 is out of bounds for axis 0 with size 0
```
Likewise with negative population sizes:
```
sim = cv.Sim(pop_size=-1)

sim.run()
Initializing sim with -1 people for 60 days
Traceback (most recent call last):

  File "<ipython-input-11-7c6cd8add6f4>", line 1, in <module>
    sim.run()

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 380, in run
    self.initialize()

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 137, in initialize
    self.init_people(**kwargs) # Create all the people (slow)

  File "/home/cliffk/idm/covasim/covasim/sim.py", line 256, in init_people
    cvpop.make_people(self, verbose=verbose, **kwargs)

  File "/home/cliffk/idm/covasim/covasim/population.py", line 60, in make_people
    popdict = make_randpop(sim, microstructure=pop_type)

  File "/home/cliffk/idm/covasim/covasim/population.py", line 99, in make_randpop
    sexes = np.random.binomial(1, sex_ratio, pop_size)

  File "mtrand.pyx", line 3383, in numpy.random.mtrand.RandomState.binomial

ValueError: negative dimensions are not allowed
```
It's not clear to me where the user would accidentally set both the population size and the number of seed infections to zero, and that they would be helped more by an exception than the current result of zero counts for everything.
